#
# Mesos masters
#
---
- hosts: masters
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
    - { role: "zookeeper", tags: "zookeeper" }
    - { role: "mesos", mesos_type: "master", tags: "mesos" }
    - { role: "marathon", tags: "marathon" }

- hosts: masters[0]
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
    - { role: "docker", tags: "docker" }
    - { role: "marathon-lb", tags: "marathon-lb" }
